module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "CabecalhoSite",
    ()=>CabecalhoSite
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CabecalhoSite = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CabecalhoSite() from the server but CabecalhoSite is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/componentes/CabecalhoSite.tsx <module evaluation>", "CabecalhoSite");
}),
"[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "CabecalhoSite",
    ()=>CabecalhoSite
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CabecalhoSite = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CabecalhoSite() from the server but CabecalhoSite is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/componentes/CabecalhoSite.tsx", "CabecalhoSite");
}),
"[project]/componentes/CabecalhoSite.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/componentes/LogotipoCriario.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "LogotipoCriario",
    ()=>LogotipoCriario
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
function LogotipoCriario({ invertido = false }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
        className: `logotipo-criario${invertido ? ' logotipo-criario--invertido' : ''}`,
        children: "CRIÁRIO"
    }, void 0, false, {
        fileName: "[project]/componentes/LogotipoCriario.tsx",
        lineNumber: 7,
        columnNumber: 5
    }, this);
}
}),
"[project]/componentes/RodapeSite.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "copyright": "RodapeSite-module__WV_vJG__copyright",
  "especialistas": "RodapeSite-module__WV_vJG__especialistas",
  "links": "RodapeSite-module__WV_vJG__links",
  "marca": "RodapeSite-module__WV_vJG__marca",
  "rodape": "RodapeSite-module__WV_vJG__rodape",
});
}),
"[project]/componentes/RodapeSite.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "RodapeSite",
    ()=>RodapeSite
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$LogotipoCriario$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/LogotipoCriario.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/componentes/RodapeSite.module.css [app-rsc] (css module)");
;
;
;
function RodapeSite() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("footer", {
        className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].rodape,
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].marca,
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$LogotipoCriario$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LogotipoCriario"], {}, void 0, false, {
                    fileName: "[project]/componentes/RodapeSite.tsx",
                    lineNumber: 7,
                    columnNumber: 37
                }, this)
            }, void 0, false, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 7,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].links,
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                        href: "#inicio",
                        children: "→   Home"
                    }, void 0, false, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 9,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                        href: "#servicos",
                        children: "→   Serviços"
                    }, void 0, false, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 10,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                        href: "#cases",
                        children: "→   Cases de sucesso"
                    }, void 0, false, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 11,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                        href: "#fale-conosco",
                        children: "→   Fale conosco"
                    }, void 0, false, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 12,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 8,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].especialistas,
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                        children: [
                            "Fale com nossos",
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("br", {}, void 0, false, {
                                fileName: "[project]/componentes/RodapeSite.tsx",
                                lineNumber: 15,
                                columnNumber: 30
                            }, this),
                            "especialistas"
                        ]
                    }, void 0, true, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 15,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                        href: "#fale-conosco",
                        "aria-label": "Falar com nossos especialistas pelo WhatsApp",
                        children: "◉"
                    }, void 0, false, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 16,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 14,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].copyright,
                children: "Criário. Todos os direitos reservados."
            }, void 0, false, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 18,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/componentes/RodapeSite.tsx",
        lineNumber: 6,
        columnNumber: 5
    }, this);
}
}),
"[project]/componentes/FaleConosco.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "faleConosco": "FaleConosco-module__ZByEpq__faleConosco",
});
}),
"[project]/componentes/FaleConosco.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "FaleConosco",
    ()=>FaleConosco
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/componentes/FaleConosco.module.css [app-rsc] (css module)");
;
;
function FaleConosco() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
        className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].faleConosco,
        href: "#fale-conosco",
        children: [
            "fale conosco ",
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                "aria-hidden": "true",
                children: "→"
            }, void 0, false, {
                fileName: "[project]/componentes/FaleConosco.tsx",
                lineNumber: 6,
                columnNumber: 20
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/componentes/FaleConosco.tsx",
        lineNumber: 5,
        columnNumber: 5
    }, this);
}
}),
"[project]/dados/cases.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "casesEmDestaque",
    ()=>casesEmDestaque
]);
const casesEmDestaque = [
    {
        cliente: 'Onboard',
        contexto: 'O futuro da bilhetagem',
        resumo: 'Como a ONBOARD passou a se mostrar à altura da própria tecnologia. Startup criadora da bilhetagem digital e top 100 do setor de mobilidade urbana.',
        imagem: '/images/case-onboard.png'
    },
    {
        cliente: 'New Era',
        contexto: 'O novo vendedor',
        resumo: 'Como as franquias New Era passaram a vender onde o cliente está. 12 franquias e uma marca global de vestuário com uma herança esportiva autêntica há 100 anos.',
        imagem: '/images/case-new-era.png'
    },
    {
        cliente: 'Pitec',
        contexto: 'Cada detalhe conta',
        resumo: 'Como a Criário redesenhou o detector científico da PITEC dentro de restrições rígidas. A grande nacional da área de fotônica, oferece detectores de raio-x para aplicações científicas.',
        imagem: '/images/case-pitec.png'
    }
];
}),
"[project]/dados/depoimentos.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "depoimentos",
    ()=>depoimentos
]);
const depoimentos = [
    {
        nome: 'Paulo Bertolo',
        cargo: 'Diretor de Operações, Pitec',
        citacao: 'Sempre senti falta de um olhar mais focado no usuário, nosso produto era menos apresentável e vendável do que poderia. Na Criário encontrei a junção de qualidade no trabalho e flexibilidade, e isso tem muito valor para mim.',
        imagem: '/images/depoimento-paulo.png',
        alinhamento: 'direita'
    },
    {
        nome: 'Luiz Renato',
        cargo: 'CEO, Onboard',
        citacao: 'Contratamos a Criário para projetar o design do DBD (Dispositivo de Bilhetagem Digital) e o resultado foi incrível. O produto saiu completamente transformado depois do trabalho deles. Além da qualidade, seu profissionalismo também foi algo que nos agradou muito. Rodrigo foi sempre muito solícito e pontual com as entregas, não poderíamos estar mais satisfeitos.',
        imagem: '/images/depoimento-luiz.png',
        alinhamento: 'esquerda'
    },
    {
        nome: 'Igor Pinheiro',
        cargo: 'Business Development, Idea',
        citacao: 'Estávamos com necessidades urgentes e precisávamos de um parceiro de confiança. Além de nos atender muito bem a Criário nos orientou e entregou o trabalho com excelência. Decidimos fortalecer a parceria de longo prazo.',
        imagem: '/images/depoimento-igor.png',
        alinhamento: 'esquerda'
    }
];
}),
"[project]/dados/clientes.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "logotiposDeClientes",
    ()=>logotiposDeClientes
]);
const logotiposDeClientes = '/images/logos-clientes.png';
}),
"[project]/funcionalidades/cases/CartaoResumoDeCase.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CartaoResumoDeCase",
    ()=>CartaoResumoDeCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
function CartaoResumoDeCase({ cliente, contexto, resumo, imagem }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("article", {
        className: "cartao-case",
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "cartao-case__imagem",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                    src: imagem,
                    alt: `Projeto desenvolvido para ${cliente}`
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                    lineNumber: 9,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                lineNumber: 8,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "cartao-case__texto",
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                        children: contexto
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                        lineNumber: 12,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h3", {
                        children: cliente
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                        lineNumber: 13,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                        children: resumo
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                        lineNumber: 14,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                lineNumber: 11,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
        lineNumber: 7,
        columnNumber: 5
    }, this);
}
}),
"[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "DepoimentoDeCliente",
    ()=>DepoimentoDeCliente
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
function DepoimentoDeCliente({ nome, cargo, citacao, imagem, alinhamento }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("article", {
        className: `depoimento depoimento--${alinhamento}`,
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "depoimento__imagem",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                    src: imagem,
                    alt: `Retrato de ${nome}`
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                    lineNumber: 9,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                lineNumber: 8,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "depoimento__texto",
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h3", {
                        children: nome
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                        lineNumber: 12,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("strong", {
                        children: cargo
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                        lineNumber: 13,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                        children: [
                            "“",
                            citacao,
                            "”"
                        ]
                    }, void 0, true, {
                        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                        lineNumber: 14,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                lineNumber: 11,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
        lineNumber: 7,
        columnNumber: 5
    }, this);
}
}),
"[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "FormularioDeContato",
    ()=>FormularioDeContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const FormularioDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call FormularioDeContato() from the server but FormularioDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/FormularioDeContato.tsx <module evaluation>", "FormularioDeContato");
}),
"[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "FormularioDeContato",
    ()=>FormularioDeContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const FormularioDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call FormularioDeContato() from the server but FormularioDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/FormularioDeContato.tsx", "FormularioDeContato");
}),
"[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/funcionalidades/contato/SecaoFaleConosco.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "SecaoFaleConosco",
    ()=>SecaoFaleConosco
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (ecmascript)");
;
;
function SecaoFaleConosco() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
        id: "fale-conosco",
        className: "secao-contato",
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "secao-contato__titulo",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                    children: "Fale conosco"
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                    lineNumber: 7,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                lineNumber: 6,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "secao-contato__painel",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["FormularioDeContato"], {}, void 0, false, {
                    fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                    lineNumber: 10,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                lineNumber: 9,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
        lineNumber: 5,
        columnNumber: 5
    }, this);
}
}),
"[project]/funcionalidades/pagina-inicial/PaginaInicial.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "apresentacao": "PaginaInicial-module__Bz8Dbq__apresentacao",
  "apresentacaoImagem": "PaginaInicial-module__Bz8Dbq__apresentacaoImagem",
  "apresentacaoTexto": "PaginaInicial-module__Bz8Dbq__apresentacaoTexto",
  "cartao-case": "PaginaInicial-module__Bz8Dbq__cartao-case",
  "cartao-case__imagem": "PaginaInicial-module__Bz8Dbq__cartao-case__imagem",
  "cartao-case__texto": "PaginaInicial-module__Bz8Dbq__cartao-case__texto",
  "cases": "PaginaInicial-module__Bz8Dbq__cases",
  "casesGrade": "PaginaInicial-module__Bz8Dbq__casesGrade",
  "casesIntro": "PaginaInicial-module__Bz8Dbq__casesIntro",
  "chamada": "PaginaInicial-module__Bz8Dbq__chamada",
  "depoimento": "PaginaInicial-module__Bz8Dbq__depoimento",
  "depoimento--direita": "PaginaInicial-module__Bz8Dbq__depoimento--direita",
  "depoimento__imagem": "PaginaInicial-module__Bz8Dbq__depoimento__imagem",
  "depoimento__texto": "PaginaInicial-module__Bz8Dbq__depoimento__texto",
  "depoimentos": "PaginaInicial-module__Bz8Dbq__depoimentos",
  "depoimentosGrade": "PaginaInicial-module__Bz8Dbq__depoimentosGrade",
  "depoimentosIntro": "PaginaInicial-module__Bz8Dbq__depoimentosIntro",
  "etapa-processo": "PaginaInicial-module__Bz8Dbq__etapa-processo",
  "etapa-processo__numero": "PaginaInicial-module__Bz8Dbq__etapa-processo__numero",
  "etapasDoProcesso": "PaginaInicial-module__Bz8Dbq__etapasDoProcesso",
  "faleConoscoContainer": "PaginaInicial-module__Bz8Dbq__faleConoscoContainer",
  "logotipos": "PaginaInicial-module__Bz8Dbq__logotipos",
  "manifesto": "PaginaInicial-module__Bz8Dbq__manifesto",
  "pagina": "PaginaInicial-module__Bz8Dbq__pagina",
  "secao-contato__titulo": "PaginaInicial-module__Bz8Dbq__secao-contato__titulo",
  "servicos": "PaginaInicial-module__Bz8Dbq__servicos",
  "servicosDescricao": "PaginaInicial-module__Bz8Dbq__servicosDescricao",
  "telaServicos": "PaginaInicial-module__Bz8Dbq__telaServicos",
});
}),
"[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "PaginaInicial",
    ()=>PaginaInicial
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/CabecalhoSite.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/RodapeSite.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/FaleConosco.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$cases$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/dados/cases.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$depoimentos$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/dados/depoimentos.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$clientes$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/dados/clientes.ts [app-rsc] (ecmascript)");
(()=>{
    const e = new Error("Cannot find module '../servicos/SecaoServicos'");
    e.code = 'MODULE_NOT_FOUND';
    throw e;
})();
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/cases/CartaoResumoDeCase.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$depoimentos$2f$DepoimentoDeCliente$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$SecaoFaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/SecaoFaleConosco.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/funcionalidades/pagina-inicial/PaginaInicial.module.css [app-rsc] (css module)");
;
;
;
;
;
;
;
;
;
;
;
;
function PaginaInicial() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].pagina,
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CabecalhoSite"], {}, void 0, false, {
                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                lineNumber: 16,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("main", {
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                        id: "inicio",
                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].apresentacao,
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].apresentacaoImagem
                            }, void 0, false, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 20,
                                columnNumber: 11
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].apresentacaoTexto,
                                children: [
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h1", {
                                        children: "Existimos porque toda empresa boa tem mais valor do que o mercado consegue ver."
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 22,
                                        columnNumber: 13
                                    }, this),
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                        children: "Nós o encontramos, refinamos e conduzimos até o consumidor final. Para quem quer construir uma vantagem competitiva que o mercado não consegue copiar."
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 23,
                                        columnNumber: 13
                                    }, this),
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].faleConoscoContainer,
                                        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["FaleConosco"], {}, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 25,
                                            columnNumber: 15
                                        }, this)
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 24,
                                        columnNumber: 13
                                    }, this)
                                ]
                            }, void 0, true, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 21,
                                columnNumber: 11
                            }, this)
                        ]
                    }, void 0, true, {
                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                        lineNumber: 19,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(SecaoServicos, {}, void 0, false, {
                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                        lineNumber: 30,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                        id: "cases",
                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].cases,
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].casesIntro,
                                children: [
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                                        children: "Construindo resultados com nossos clientes."
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 34,
                                        columnNumber: 13
                                    }, this),
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                        children: "Ciclo de vendas longo, produto que não converte, imagem que não reflete a qualidade de entrega. Visão centrada no ser humano para projetos reais e problemas reais."
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 35,
                                        columnNumber: 13
                                    }, this)
                                ]
                            }, void 0, true, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 33,
                                columnNumber: 11
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].casesGrade,
                                children: __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$cases$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["casesEmDestaque"].map((item)=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CartaoResumoDeCase"], {
                                        ...item
                                    }, item.cliente, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 38,
                                        columnNumber: 44
                                    }, this))
                            }, void 0, false, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 37,
                                columnNumber: 11
                            }, this)
                        ]
                    }, void 0, true, {
                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                        lineNumber: 32,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].depoimentos,
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].depoimentosIntro,
                                children: [
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                                        children: "Quem já trabalhou com a Criário."
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 44,
                                        columnNumber: 13
                                    }, this),
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                        children: "Empresas que reconheceram o gap entre o valor que entregavam e o que o mercado percebia, e decidiram fazer algo a respeito."
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 45,
                                        columnNumber: 13
                                    }, this)
                                ]
                            }, void 0, true, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 43,
                                columnNumber: 11
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].depoimentosGrade,
                                children: __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$depoimentos$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["depoimentos"].map((item)=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$depoimentos$2f$DepoimentoDeCliente$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DepoimentoDeCliente"], {
                                        ...item
                                    }, item.nome, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 48,
                                        columnNumber: 40
                                    }, this))
                            }, void 0, false, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 47,
                                columnNumber: 11
                            }, this)
                        ]
                    }, void 0, true, {
                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                        lineNumber: 42,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].logotipos,
                        "aria-label": "Clientes da Criário",
                        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                            src: __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$clientes$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["logotiposDeClientes"],
                            alt: "Logotipos de clientes da Criário"
                        }, void 0, false, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 53,
                            columnNumber: 11
                        }, this)
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                        lineNumber: 52,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].manifesto,
                        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                            children: [
                                "Para você que acredita que alguns problemas exigem ",
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("em", {
                                    children: "invenção genuína"
                                }, void 0, false, {
                                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                    lineNumber: 57,
                                    columnNumber: 65
                                }, this),
                                " em vez da aplicação de modelos pré-estabelecidos."
                            ]
                        }, void 0, true, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 57,
                            columnNumber: 11
                        }, this)
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                        lineNumber: 56,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$SecaoFaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SecaoFaleConosco"], {}, void 0, false, {
                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                        lineNumber: 60,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                lineNumber: 18,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["RodapeSite"], {}, void 0, false, {
                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                lineNumber: 63,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
        lineNumber: 15,
        columnNumber: 5
    }, this);
}
}),
"[project]/app/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>Home
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx [app-rsc] (ecmascript)");
;
;
function Home() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PaginaInicial"], {}, void 0, false, {
        fileName: "[project]/app/page.tsx",
        lineNumber: 4,
        columnNumber: 10
    }, this);
}
}),
"[project]/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__3c743321._.js.map