module.exports = [
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/app/(portugues)/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/(portugues)/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "CabecalhoSite",
    ()=>CabecalhoSite
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CabecalhoSite = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CabecalhoSite() from the server but CabecalhoSite is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/componentes/CabecalhoSite.tsx <module evaluation>", "CabecalhoSite");
}),
"[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "CabecalhoSite",
    ()=>CabecalhoSite
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const CabecalhoSite = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call CabecalhoSite() from the server but CabecalhoSite is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/componentes/CabecalhoSite.tsx", "CabecalhoSite");
}),
"[project]/componentes/CabecalhoSite.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/componentes/CabecalhoSite.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/componentes/LogotipoCriario.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "LogotipoCriario",
    ()=>LogotipoCriario
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
function LogotipoCriario({ texto, invertido = false }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
        className: `logotipo-criario${invertido ? ' logotipo-criario--invertido' : ''}`,
        children: texto
    }, void 0, false, {
        fileName: "[project]/componentes/LogotipoCriario.tsx",
        lineNumber: 8,
        columnNumber: 5
    }, this);
}
}),
"[project]/componentes/RodapeSite.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "copyright": "RodapeSite-module__WV_vJG__copyright",
  "especialistas": "RodapeSite-module__WV_vJG__especialistas",
  "links": "RodapeSite-module__WV_vJG__links",
  "marca": "RodapeSite-module__WV_vJG__marca",
  "rodape": "RodapeSite-module__WV_vJG__rodape",
});
}),
"[project]/dados/navegacao.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "itensDeNavegacao",
    ()=>itensDeNavegacao
]);
const itensDeNavegacao = [
    {
        numero: '01',
        id: 'inicio',
        destino: 'inicio'
    },
    {
        numero: '02',
        id: 'servicos',
        destino: 'servicos'
    },
    {
        numero: '03',
        id: 'cases',
        destino: 'cases'
    },
    {
        numero: '04',
        id: 'contato',
        destino: 'fale-conosco'
    }
];
}),
"[project]/funcionalidades/contato/LinkDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "LinkDeContato",
    ()=>LinkDeContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const LinkDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call LinkDeContato() from the server but LinkDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/LinkDeContato.tsx <module evaluation>", "LinkDeContato");
}),
"[project]/funcionalidades/contato/LinkDeContato.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "LinkDeContato",
    ()=>LinkDeContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const LinkDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call LinkDeContato() from the server but LinkDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/LinkDeContato.tsx", "LinkDeContato");
}),
"[project]/funcionalidades/contato/LinkDeContato.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/funcionalidades/contato/LinkDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/LinkDeContato.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/componentes/RodapeSite.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "RodapeSite",
    ()=>RodapeSite
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$LogotipoCriario$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/LogotipoCriario.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/componentes/RodapeSite.module.css [app-rsc] (css module)");
var __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$navegacao$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/dados/navegacao.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/LinkDeContato.tsx [app-rsc] (ecmascript)");
;
;
;
;
;
function RodapeSite({ textos }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("footer", {
        className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].rodape,
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].marca,
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$LogotipoCriario$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LogotipoCriario"], {
                    texto: textos.marca
                }, void 0, false, {
                    fileName: "[project]/componentes/RodapeSite.tsx",
                    lineNumber: 10,
                    columnNumber: 37
                }, this)
            }, void 0, false, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 10,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].links,
                children: __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$navegacao$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["itensDeNavegacao"].map(({ id, destino })=>destino === 'fale-conosco' ? /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LinkDeContato"], {
                        children: [
                            "→   ",
                            textos.navegacao[id]
                        ]
                    }, id, true, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 13,
                        columnNumber: 13
                    }, this) : /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("a", {
                        href: '#' + destino,
                        children: [
                            "→   ",
                            textos.navegacao[id]
                        ]
                    }, id, true, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 14,
                        columnNumber: 13
                    }, this))
            }, void 0, false, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 11,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].especialistas,
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                        children: textos.rodape.especialistas
                    }, void 0, false, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 17,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LinkDeContato"], {
                        "aria-label": textos.rodape.especialistasRotulo,
                        children: "◉"
                    }, void 0, false, {
                        fileName: "[project]/componentes/RodapeSite.tsx",
                        lineNumber: 18,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 16,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].copyright,
                children: textos.rodape.copyright
            }, void 0, false, {
                fileName: "[project]/componentes/RodapeSite.tsx",
                lineNumber: 20,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/componentes/RodapeSite.tsx",
        lineNumber: 9,
        columnNumber: 5
    }, this);
}
}),
"[project]/componentes/FaleConosco.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "faleConosco": "FaleConosco-module__ZByEpq__faleConosco",
});
}),
"[project]/componentes/FaleConosco.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "FaleConosco",
    ()=>FaleConosco
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/componentes/FaleConosco.module.css [app-rsc] (css module)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/LinkDeContato.tsx [app-rsc] (ecmascript)");
;
;
;
function FaleConosco({ texto }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$LinkDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["LinkDeContato"], {
        className: __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].faleConosco,
        children: [
            texto,
            " ",
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                "aria-hidden": "true",
                children: "→"
            }, void 0, false, {
                fileName: "[project]/componentes/FaleConosco.tsx",
                lineNumber: 7,
                columnNumber: 15
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/componentes/FaleConosco.tsx",
        lineNumber: 6,
        columnNumber: 5
    }, this);
}
}),
"[project]/dados/cases.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "casesEmDestaque",
    ()=>casesEmDestaque
]);
const casesEmDestaque = [
    {
        id: 'onboard',
        imagem: '/images/case-onboard.png'
    },
    {
        id: 'newEra',
        imagem: '/images/case-new-era.png'
    },
    {
        id: 'pitec',
        imagem: '/images/case-pitec.png'
    }
];
}),
"[project]/dados/depoimentos.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "depoimentos",
    ()=>depoimentos
]);
const depoimentos = [
    {
        id: 'paulo',
        imagem: '/images/depoimento-paulo.png',
        alinhamento: 'direita'
    },
    {
        id: 'luiz',
        imagem: '/images/depoimento-luiz.png',
        alinhamento: 'esquerda'
    },
    {
        id: 'igor',
        imagem: '/images/depoimento-igor-pinheiro.png',
        alinhamento: 'direita'
    }
];
}),
"[project]/dados/clientes.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "logotiposDeClientes",
    ()=>logotiposDeClientes
]);
const logotiposDeClientes = '/images/logos-clientes.png';
}),
"[project]/funcionalidades/servicos/SecaoServicos.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "SecaoServicos",
    ()=>SecaoServicos
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const SecaoServicos = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call SecaoServicos() from the server but SecaoServicos is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/servicos/SecaoServicos.tsx <module evaluation>", "SecaoServicos");
}),
"[project]/funcionalidades/servicos/SecaoServicos.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "SecaoServicos",
    ()=>SecaoServicos
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const SecaoServicos = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call SecaoServicos() from the server but SecaoServicos is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/servicos/SecaoServicos.tsx", "SecaoServicos");
}),
"[project]/funcionalidades/servicos/SecaoServicos.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$servicos$2f$SecaoServicos$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/funcionalidades/servicos/SecaoServicos.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$servicos$2f$SecaoServicos$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/funcionalidades/servicos/SecaoServicos.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$servicos$2f$SecaoServicos$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/funcionalidades/cases/CartaoResumoDeCase.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "cabecalho": "CartaoResumoDeCase-module__QeOCEG__cabecalho",
  "cartao": "CartaoResumoDeCase-module__QeOCEG__cartao",
  "contexto": "CartaoResumoDeCase-module__QeOCEG__contexto",
  "mais": "CartaoResumoDeCase-module__QeOCEG__mais",
  "texto": "CartaoResumoDeCase-module__QeOCEG__texto",
});
}),
"[project]/funcionalidades/cases/CartaoResumoDeCase.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CartaoResumoDeCase",
    ()=>CartaoResumoDeCase
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/funcionalidades/cases/CartaoResumoDeCase.module.css [app-rsc] (css module)");
;
;
function CartaoResumoDeCase({ cliente, contexto, resumo, imagem, imagemAlt }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("article", {
        className: `cartao-case ${__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].cartao}`,
        tabIndex: 0,
        "aria-label": cliente,
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "cartao-case__imagem",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                    src: imagem,
                    alt: imagemAlt
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                    lineNumber: 10,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                lineNumber: 9,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: `cartao-case__texto ${__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].texto}`,
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].cabecalho,
                        children: [
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                children: [
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                                        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].contexto,
                                        children: contexto
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                                        lineNumber: 15,
                                        columnNumber: 13
                                    }, this),
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h3", {
                                        children: cliente
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                                        lineNumber: 16,
                                        columnNumber: 13
                                    }, this)
                                ]
                            }, void 0, true, {
                                fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                                lineNumber: 14,
                                columnNumber: 11
                            }, this),
                            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].mais,
                                "aria-hidden": "true",
                                children: "+"
                            }, void 0, false, {
                                fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                                lineNumber: 18,
                                columnNumber: 11
                            }, this)
                        ]
                    }, void 0, true, {
                        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                        lineNumber: 13,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                        children: resumo
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                        lineNumber: 20,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
                lineNumber: 12,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/cases/CartaoResumoDeCase.tsx",
        lineNumber: 8,
        columnNumber: 5
    }, this);
}
}),
"[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "DepoimentoDeCliente",
    ()=>DepoimentoDeCliente
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
function DepoimentoDeCliente({ nome, cargo, citacao, imagem, imagemAlt, alinhamento }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("article", {
        className: `depoimento depoimento--${alinhamento}`,
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "depoimento__imagem",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                    src: imagem,
                    alt: imagemAlt
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                    lineNumber: 9,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                lineNumber: 8,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "depoimento__texto",
                children: [
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h3", {
                        children: nome
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                        lineNumber: 12,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("strong", {
                        children: cargo
                    }, void 0, false, {
                        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                        lineNumber: 13,
                        columnNumber: 9
                    }, this),
                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                        children: [
                            "“",
                            citacao,
                            "”"
                        ]
                    }, void 0, true, {
                        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                        lineNumber: 14,
                        columnNumber: 9
                    }, this)
                ]
            }, void 0, true, {
                fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
                lineNumber: 11,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx",
        lineNumber: 7,
        columnNumber: 5
    }, this);
}
}),
"[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "FormularioDeContato",
    ()=>FormularioDeContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const FormularioDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call FormularioDeContato() from the server but FormularioDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/FormularioDeContato.tsx <module evaluation>", "FormularioDeContato");
}),
"[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "FormularioDeContato",
    ()=>FormularioDeContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const FormularioDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call FormularioDeContato() from the server but FormularioDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/FormularioDeContato.tsx", "FormularioDeContato");
}),
"[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/funcionalidades/contato/Contato.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "alternativa": "Contato-module__MkxF-q__alternativa",
  "aparecer": "Contato-module__MkxF-q__aparecer",
  "armadilha": "Contato-module__MkxF-q__armadilha",
  "campos": "Contato-module__MkxF-q__campos",
  "cartao": "Contato-module__MkxF-q__cartao",
  "enviar": "Contato-module__MkxF-q__enviar",
  "erro": "Contato-module__MkxF-q__erro",
  "fechar": "Contato-module__MkxF-q__fechar",
  "formulario": "Contato-module__MkxF-q__formulario",
  "modal": "Contato-module__MkxF-q__modal",
  "necessidade": "Contato-module__MkxF-q__necessidade",
  "sucesso": "Contato-module__MkxF-q__sucesso",
});
}),
"[project]/funcionalidades/contato/CartaoDeContato.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "CartaoDeContato",
    ()=>CartaoDeContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/FormularioDeContato.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$Contato$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/Contato.module.css [app-rsc] (css module)");
;
;
;
function CartaoDeContato({ textos, aoFechar }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
        className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$Contato$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].cartao,
        children: [
            aoFechar && /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("button", {
                className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$Contato$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].fechar,
                type: "button",
                onClick: aoFechar,
                "aria-label": textos.fechar,
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("span", {
                    "aria-hidden": "true",
                    children: "×"
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/contato/CartaoDeContato.tsx",
                    lineNumber: 11,
                    columnNumber: 114
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/contato/CartaoDeContato.tsx",
                lineNumber: 11,
                columnNumber: 20
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$FormularioDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["FormularioDeContato"], {
                textos: textos.formulario
            }, void 0, false, {
                fileName: "[project]/funcionalidades/contato/CartaoDeContato.tsx",
                lineNumber: 12,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/contato/CartaoDeContato.tsx",
        lineNumber: 10,
        columnNumber: 5
    }, this);
}
}),
"[project]/funcionalidades/contato/SecaoFaleConosco.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "SecaoFaleConosco",
    ()=>SecaoFaleConosco
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$CartaoDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/CartaoDeContato.tsx [app-rsc] (ecmascript)");
;
;
function SecaoFaleConosco({ textos }) {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
        id: "fale-conosco",
        className: "secao-contato",
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "secao-contato__titulo",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                    children: textos.titulo
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                    lineNumber: 8,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                lineNumber: 7,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                className: "secao-contato__painel",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$CartaoDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CartaoDeContato"], {
                    textos: textos
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                    lineNumber: 11,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
                lineNumber: 10,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/funcionalidades/contato/SecaoFaleConosco.tsx",
        lineNumber: 6,
        columnNumber: 5
    }, this);
}
}),
"[project]/funcionalidades/pagina-inicial/PaginaInicial.module.css [app-rsc] (css module)", ((__turbopack_context__) => {

__turbopack_context__.v({
  "apresentacao": "PaginaInicial-module__Bz8Dbq__apresentacao",
  "apresentacaoImagem": "PaginaInicial-module__Bz8Dbq__apresentacaoImagem",
  "apresentacaoTexto": "PaginaInicial-module__Bz8Dbq__apresentacaoTexto",
  "cartao-case": "PaginaInicial-module__Bz8Dbq__cartao-case",
  "cartao-case__imagem": "PaginaInicial-module__Bz8Dbq__cartao-case__imagem",
  "cartao-case__texto": "PaginaInicial-module__Bz8Dbq__cartao-case__texto",
  "cases": "PaginaInicial-module__Bz8Dbq__cases",
  "casesGrade": "PaginaInicial-module__Bz8Dbq__casesGrade",
  "casesIntro": "PaginaInicial-module__Bz8Dbq__casesIntro",
  "chamada": "PaginaInicial-module__Bz8Dbq__chamada",
  "depoimento": "PaginaInicial-module__Bz8Dbq__depoimento",
  "depoimento--direita": "PaginaInicial-module__Bz8Dbq__depoimento--direita",
  "depoimento__imagem": "PaginaInicial-module__Bz8Dbq__depoimento__imagem",
  "depoimento__texto": "PaginaInicial-module__Bz8Dbq__depoimento__texto",
  "depoimentos": "PaginaInicial-module__Bz8Dbq__depoimentos",
  "depoimentosGrade": "PaginaInicial-module__Bz8Dbq__depoimentosGrade",
  "depoimentosIntro": "PaginaInicial-module__Bz8Dbq__depoimentosIntro",
  "etapa-processo": "PaginaInicial-module__Bz8Dbq__etapa-processo",
  "etapa-processo__numero": "PaginaInicial-module__Bz8Dbq__etapa-processo__numero",
  "etapasDoProcesso": "PaginaInicial-module__Bz8Dbq__etapasDoProcesso",
  "faleConoscoContainer": "PaginaInicial-module__Bz8Dbq__faleConoscoContainer",
  "logotipos": "PaginaInicial-module__Bz8Dbq__logotipos",
  "manifesto": "PaginaInicial-module__Bz8Dbq__manifesto",
  "pagina": "PaginaInicial-module__Bz8Dbq__pagina",
  "secao-contato__titulo": "PaginaInicial-module__Bz8Dbq__secao-contato__titulo",
  "servicos": "PaginaInicial-module__Bz8Dbq__servicos",
  "servicosDescricao": "PaginaInicial-module__Bz8Dbq__servicosDescricao",
  "telaServicos": "PaginaInicial-module__Bz8Dbq__telaServicos",
});
}),
"[project]/funcionalidades/contato/ProvedorDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "ProvedorDeContato",
    ()=>ProvedorDeContato,
    "useContato",
    ()=>useContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ProvedorDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ProvedorDeContato() from the server but ProvedorDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/ProvedorDeContato.tsx <module evaluation>", "ProvedorDeContato");
const useContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call useContato() from the server but useContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/ProvedorDeContato.tsx <module evaluation>", "useContato");
}),
"[project]/funcionalidades/contato/ProvedorDeContato.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "ProvedorDeContato",
    ()=>ProvedorDeContato,
    "useContato",
    ()=>useContato
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ProvedorDeContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ProvedorDeContato() from the server but ProvedorDeContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/ProvedorDeContato.tsx", "ProvedorDeContato");
const useContato = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call useContato() from the server but useContato is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/funcionalidades/contato/ProvedorDeContato.tsx", "useContato");
}),
"[project]/funcionalidades/contato/ProvedorDeContato.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$ProvedorDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/funcionalidades/contato/ProvedorDeContato.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$ProvedorDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/ProvedorDeContato.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$ProvedorDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "PaginaInicial",
    ()=>PaginaInicial
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/CabecalhoSite.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/RodapeSite.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/componentes/FaleConosco.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$cases$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/dados/cases.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$depoimentos$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/dados/depoimentos.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$clientes$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/dados/clientes.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$servicos$2f$SecaoServicos$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/servicos/SecaoServicos.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/cases/CartaoResumoDeCase.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$depoimentos$2f$DepoimentoDeCliente$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/depoimentos/DepoimentoDeCliente.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$SecaoFaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/SecaoFaleConosco.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__ = __turbopack_context__.i("[project]/funcionalidades/pagina-inicial/PaginaInicial.module.css [app-rsc] (css module)");
var __TURBOPACK__imported__module__$5b$project$5d2f$locales$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/locales/index.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$ProvedorDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/contato/ProvedorDeContato.tsx [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
;
;
;
;
;
;
;
function PaginaInicial({ idioma }) {
    const textos = (0, __TURBOPACK__imported__module__$5b$project$5d2f$locales$2f$index$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["obterTextos"])(idioma);
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$ProvedorDeContato$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ProvedorDeContato"], {
        textos: textos.contato,
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
            className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].pagina,
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$CabecalhoSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CabecalhoSite"], {
                    textos: {
                        marca: textos.marca,
                        menu: textos.menu,
                        navegacao: textos.navegacao,
                        comum: textos.comum,
                        idiomas: textos.idiomas
                    },
                    idioma: idioma
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                    lineNumber: 20,
                    columnNumber: 7
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("main", {
                    children: [
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                            id: "inicio",
                            className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].apresentacao,
                            children: [
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].apresentacaoImagem
                                }, void 0, false, {
                                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                    lineNumber: 24,
                                    columnNumber: 11
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].apresentacaoTexto,
                                    children: [
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h1", {
                                            children: textos.apresentacao.titulo
                                        }, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 26,
                                            columnNumber: 13
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                            children: textos.apresentacao.descricao
                                        }, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 27,
                                            columnNumber: 13
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                            className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].faleConoscoContainer,
                                            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$FaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["FaleConosco"], {
                                                texto: textos.comum.faleConosco
                                            }, void 0, false, {
                                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                                lineNumber: 29,
                                                columnNumber: 15
                                            }, this)
                                        }, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 28,
                                            columnNumber: 13
                                        }, this)
                                    ]
                                }, void 0, true, {
                                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                    lineNumber: 25,
                                    columnNumber: 11
                                }, this)
                            ]
                        }, void 0, true, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 23,
                            columnNumber: 9
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$servicos$2f$SecaoServicos$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SecaoServicos"], {
                            textos: textos.servicos,
                            comum: textos.comum
                        }, void 0, false, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 34,
                            columnNumber: 9
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                            id: "cases",
                            className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].cases,
                            children: [
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].casesIntro,
                                    children: [
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                                            children: textos.cases.titulo
                                        }, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 38,
                                            columnNumber: 13
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                            children: textos.cases.descricao
                                        }, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 39,
                                            columnNumber: 13
                                        }, this)
                                    ]
                                }, void 0, true, {
                                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                    lineNumber: 37,
                                    columnNumber: 11
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].casesGrade,
                                    children: __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$cases$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["casesEmDestaque"].map(({ id, imagem })=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$cases$2f$CartaoResumoDeCase$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["CartaoResumoDeCase"], {
                                            imagem: imagem,
                                            ...textos.cases.itens[id]
                                        }, id, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 42,
                                            columnNumber: 54
                                        }, this))
                                }, void 0, false, {
                                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                    lineNumber: 41,
                                    columnNumber: 11
                                }, this)
                            ]
                        }, void 0, true, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 36,
                            columnNumber: 9
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                            className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].depoimentos,
                            children: [
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].depoimentosIntro,
                                    children: [
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h2", {
                                            children: textos.depoimentos.titulo
                                        }, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 48,
                                            columnNumber: 13
                                        }, this),
                                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                            children: textos.depoimentos.descricao
                                        }, void 0, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 49,
                                            columnNumber: 13
                                        }, this)
                                    ]
                                }, void 0, true, {
                                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                    lineNumber: 47,
                                    columnNumber: 11
                                }, this),
                                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                                    className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].depoimentosGrade,
                                    children: __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$depoimentos$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["depoimentos"].map(({ id, ...item })=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$depoimentos$2f$DepoimentoDeCliente$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DepoimentoDeCliente"], {
                                            ...item,
                                            ...textos.depoimentos.itens[id]
                                        }, id, false, {
                                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                            lineNumber: 52,
                                            columnNumber: 51
                                        }, this))
                                }, void 0, false, {
                                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                    lineNumber: 51,
                                    columnNumber: 11
                                }, this)
                            ]
                        }, void 0, true, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 46,
                            columnNumber: 9
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                            className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].logotipos,
                            "aria-label": textos.clientes.rotulo,
                            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("img", {
                                src: __TURBOPACK__imported__module__$5b$project$5d2f$dados$2f$clientes$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["logotiposDeClientes"],
                                alt: textos.clientes.imagemAlt
                            }, void 0, false, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 57,
                                columnNumber: 11
                            }, this)
                        }, void 0, false, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 56,
                            columnNumber: 9
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("section", {
                            className: __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$module$2e$css__$5b$app$2d$rsc$5d$__$28$css__module$29$__["default"].manifesto,
                            children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                                children: [
                                    textos.manifesto.antes,
                                    /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("em", {
                                        children: textos.manifesto.destaque
                                    }, void 0, false, {
                                        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                        lineNumber: 61,
                                        columnNumber: 38
                                    }, this),
                                    textos.manifesto.depois
                                ]
                            }, void 0, true, {
                                fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                                lineNumber: 61,
                                columnNumber: 11
                            }, this)
                        }, void 0, false, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 60,
                            columnNumber: 9
                        }, this),
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$contato$2f$SecaoFaleConosco$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["SecaoFaleConosco"], {
                            textos: textos.contato
                        }, void 0, false, {
                            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                            lineNumber: 64,
                            columnNumber: 9
                        }, this)
                    ]
                }, void 0, true, {
                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                    lineNumber: 22,
                    columnNumber: 7
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$componentes$2f$RodapeSite$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["RodapeSite"], {
                    textos: textos
                }, void 0, false, {
                    fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
                    lineNumber: 67,
                    columnNumber: 7
                }, this)
            ]
        }, void 0, true, {
            fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
            lineNumber: 19,
            columnNumber: 5
        }, this)
    }, void 0, false, {
        fileName: "[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx",
        lineNumber: 18,
        columnNumber: 5
    }, this);
}
}),
"[project]/app/(portugues)/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>Home
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/funcionalidades/pagina-inicial/PaginaInicial.tsx [app-rsc] (ecmascript)");
;
;
function Home() {
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$funcionalidades$2f$pagina$2d$inicial$2f$PaginaInicial$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["PaginaInicial"], {
        idioma: "pt-BR"
    }, void 0, false, {
        fileName: "[project]/app/(portugues)/page.tsx",
        lineNumber: 4,
        columnNumber: 10
    }, this);
}
}),
"[project]/app/(portugues)/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/app/(portugues)/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__3d130812._.js.map